name: flutter_test_login_register
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_splash_screen:
  bubble: ^1.2.1
  calendar_timeline: ^0.7.1
  camera: ^0.9.4+5
  country_pickers: ^2.0.0
  contacts_service: ^0.6.3
  custom_image_picker: ^0.5.0
  date_format: ^2.0.4
  date_time: ^0.4.5
  ext_storage: ^1.0.3
  file_picker: ^4.2.4
  firestore_search: ^0.1.7
  flutter_downloader: ^1.7.1
  flutter_slidable: ^0.5.7
  flutter_svg: ^0.23.0+1
  flutter_bloc:
  geocoding: ^2.0.1
  geocoder: ^0.2.1
  geoflutterfire: ^3.0.1
  geolocator: ^7.7.1
  get_rx: ^3.13.0
  getwidget: ^2.0.4
  intl:
  location: ^4.3.0
  multilevel_drawer: ^2.0.0
  google_fonts: ^2.1.0
  google_maps_flutter: ^2.0.2
  cached_network_image: ^3.0.0
  cloud_firestore: ^2.3.0
  convex_bottom_bar: ^3.0.0
  firebase_auth: ^1.1.0
  provider: ^5.0.0
  shared_preferences: ^2.0.5
  random_string: ^2.1.0
  firebase_core: ^1.0.3
  lipsum: ^1.0.1
  url_launcher: ^6.0.3
  polls: ^1.0.1
  percent_indicator: ^3.0.1
  image_picker:
  firebase_storage:
  flutter_image_compress:
  path_provider:
  uuid:
  firebase_admob: ^0.11.2
  font_awesome_flutter: ^9.1.0
  firebase_messaging: ^10.0.2
  flutter_local_notifications: ^5.0.0+4
  flutter_spinkit: ^4.1.2+1
  dio: ^4.0.0
  webview_flutter: ^1.0.0
  js: ^0.6.2
  threading: ^0.0.10
  flutter_launcher_icons: ^0.9.0
  fluttertoast: ^8.0.8
  flutter_polyline_points: ^0.2.6
  get_it: ^4.0.4
  open_file: ^3.2.1
  page_transition: ^1.1.7+2
  permission_handler: ^8.3.0
  pin_code_fields: ^7.3.0
  simple_animations: ^1.3.4
  equatable: ^2.0.0



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^1.1.7


flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/Logo_Dewan_Perniagaan_Melayu_Malaysia.png"

flutter_native_splash:
  color: "#fa6948"
  image: assets/Logo_Dewan_Perniagaan_Melayu_Malaysia.png
  android: true
  ios: true



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
        - asset: assets/fonts/OpenSans-BoldItalic.ttf
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
        - asset: assets/fonts/OpenSans-ExtraBoldItalic.ttf
        - asset: assets/fonts/OpenSans-Italic.ttf
        - asset: assets/fonts/OpenSans-Light.ttf
        - asset: assets/fonts/OpenSans-LightItalic.ttf
        - asset: assets/fonts/OpenSans-Medium.ttf
        - asset: assets/fonts/OpenSans-MediumItalic.ttf
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-SemiBold.ttf
        - asset: assets/fonts/OpenSans-SemiBoldItalic.ttf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/Logo_Dewan_Perniagaan_Melayu_Malaysia.png
    - assets/Logo_Dewan_Perniagaan_Melayu_Malaysia.png
    - assets/splash.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
